# Target infra : Haproxy > n * ghost > db 
# additional: elk + promotheus + piwik
# At first one overlay network > evoluating toward seggregated networks

# lb:
#   image: haproxy
#   ports:
#     - "80:80"
#     - "443:443"
#   volumes:
#     - config
#     - cert

ghost:
  image: ghost
  ports:
    - 2368
  volumes:
    # - $PWD/blog/config.js:/var/lib/ghost/config.js
    - /home/ubuntu/config.js:/var/lib/ghost/config.js
  links:
    - db
  environment:
    - NODE_ENV=production
    - DB_URI=swarm_db_1

db:
  image: postgres:9.3
  environment:
    DB_PASSWORD: postgres
    DB_USER: postgres
    DB_NAME: ghost
  ports:
    - "5432:5432"
