# Target infra : Haproxy > n * ghost > db 
ghost:
  image: ghost
  restart: always
  ports:
    - 2368
  volumes:
    - /home/ubuntu/conf-files/config.js:/var/lib/ghost/config.js
  environment:
    - DB_URI=swarm_db_1
    - NODE_ENV=production
  log_driver: "syslog"
  log_opt:
    syslog-address: "udp://185.19.29.213:5000"
    syslog-tag: "ghost"

db:
  image: postgres:9.3
  restart: always
  environment:
    DB_PASSWORD: postgres
    DB_USER: postgres
    DB_NAME: ghost
  ports:
    - 5432

lb:
  image: lalu/haproxy-consul
  restart: always
  volumes:
    - /home/ubuntu/conf-files/haproxy.ctmpl:/tmp/haproxy.ctmpl
    - /home/ubuntu/conf-files/consule-template.conf:/tmp/consule-template.conf
  ports:
    - "80:80"
    - "8001:8001"
  command: -consul 185.19.29.213:8500


