# Target infra : Haproxy > n * ghost > db 
# additional: elk + promotheus + piwik
# At first one overlay network > evoluating toward seggregated networks

# lb:
#   image: haproxy
#   ports:
#     - "80:80"
#     - "443:443"
#   volumes:
#     - config
#     - cert

ghost:
  image: ghost
  ports:
    - "80:2368"
  volumes:
    # - $PWD/blog/config.js:/var/lib/ghost/config.js
    - /home/ubuntu/config.js:/var/lib/ghost/config.js
  links:
    - db
  environment:
    - NODE_ENV=production
    - DB_URI=how2dock_db_1

db:
  image: postgres:9.3
  environment:
    DB_PASSWORD: postgres
    DB_USER: postgres
    DB_NAME: ghost
  ports:
    - "5432:5432"

# mariadb:
#   image: mariadb
#   environment:
#     MYSQL_ROOT_PASSWORD: mysqlrootpassword
#     MYSQL_USER: admin
#     MYSQL_PASSWORD: ghostpassword
#     MYSQL_DATABASE: ghost
  # volumes_from:
  #   - mariadbdata
  # log_driver: "syslog"
  # log_opt:
  #   syslog-address: "udp://localhost:5000"
  #   syslog-tag: "mariadb"