# Please run compose and init db: Initialize Database
#docker run --rm -it --link prometheus_mysql_1:db -e DATABASE_URL=mysql2://dbadmin:pw@db:3306/dash prom/promdash ./bin/rake db:migrate
version: '2'

services:
  dash:
    image: prom/promdash
    environment:
      DATABASE_URL: mysql2://dbadmin:pw@mysql:3306/dash
    ports:
      - "3000:3000"
    links:
      - mysql

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pw
      MYSQL_USER: dbadmin
      MYSQL_PASSWORD: pw
      MYSQL_DATABASE: dash

  prometheus:
    image: prom/prometheus
    volumes:
      - "/home/ubuntu/conf-files/promotheus-conf/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "/home/ubuntu/conf-files/promotheus-conf/alert.rules:/etc/prometheus/alert.rules"
    ports:
      - "9090:9090"
    command: "-config.file=/etc/prometheus/prometheus.yml -alertmanager.url=http://192.168.33.10:9093"

  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    command: "-config.file=/alertmanager.conf"
    volumes:
      - "/home/ubuntu/conf-files/promotheus-conf/alertmanager.conf:/alertmanager.conf"

# cadvisor:
#   image: google/cadvisor:latest
#   restart: always
#   ports:
#     - "8888:8080"
#   volumes:
#     - /:/rootfs:ro
#     - /var/run:/var/run:rw
#     - /sys:/sys:ro
#     - /var/lib/docker/:/var/lib/docker:ro
  #links: 
  #  - elasticsearch
#   #command: -storage_driver="elasticsearch" -alsologtostderr=true -storage_driver_es_host="http://elasticsearch:9200"

# test:
#   image: nginx
#   ports: 
#     - "80:80"

# nodeexporter:
#   image: prom/node-exporter
#   ports:
#     - "9100:9100"
#   net: host